ci: changes

diff --git a/.github/workflows/validate-code.yml b/.github/workflows/validate-code.yml
--- a/.github/workflows/validate-code.yml
+++ b/.github/workflows/validate-code.yml
@@ -32,21 +32,65 @@ jobs:
           GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
           GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
 
-  format_code:
+  code_checks:
     name: Format Code
     runs-on: ubuntu-latest
     outputs:
-      bash: ${{ steps.format_code_cmd.outputs.bash }}
+      format_code: ${{ steps.format_code.outputs.bash }}
+      lint_code: ${{ steps.lint_code.outputs.bash }}
+      lint_knip: ${{ steps.lint_knip.outputs.bash }}
+      lint_cspell: ${{ steps.lint_cspell.outputs.bash }}
+      lint_markdown: ${{ steps.lint_markdown.outputs.bash }}
+      build_packages: ${{ steps.build_packages.outputs.bash }}
+      build_packages.exitcode: ${{ steps.build_packages.outputs.exitcode }}
+      # build_website: ${{ steps.build_website.outputs.bash }}
     steps:
+      # TODO - RUN ALL STEPS EVEN IF PREVIOUS STEP FAILS AND IN PARALLEL
       - uses: actions/checkout@v4
       - uses: oven-sh/setup-bun@v2
       - run: bun install
-      - id: format_code_cmd
+      - id: format_code
         name: Format Code
         run: |
           {
             echo "bash<<EOF"
             echo "$(bun run format)"
+            echo "EOF"
+          } >> $GITHUB_OUTPUT
+      - id: lint_code
+        name: Lint Code
+        continue-on-error: true
+        run: |
+          {
+            echo "bash<<EOF"
+            echo "$(bun run lint:code)"
+            echo "EOF"
+          } >> $GITHUB_OUTPUT
+      - id: lint_knip
+        name: Lint Knip
+        continue-on-error: true
+        run: |
+          {
+            echo "bash<<EOF"
+            echo "$(bun run lint:knip --reporter markdown)"
+            echo "EOF"
+          } >> $GITHUB_OUTPUT
+      - id: lint_cspell
+        name: Lint CSpell
+        continue-on-error: true
+        run: |
+          {
+            echo "bash<<EOF"
+            echo "$(bun run lint:cspell)"
+            echo "EOF"
+          } >> $GITHUB_OUTPUT
+      - id: lint_markdown
+        name: Lint Markdown
+        continue-on-error: true
+        run: |
+          {
+            echo "bash<<EOF"
+            echo "$(bun run lint:md)"
             echo "EOF"
           } >> $GITHUB_OUTPUT
       # - name: Import GPG key
@@ -62,7 +106,6 @@ jobs:
       #     git_tag_gpgsign: true
       #     git_user_signingkey: true
       # - name: Commit changes (if any)
-      #   if: github.event_name == 'pull_request'
       #   run: |
       #     if [ -n "$(git status --porcelain)" ]; then
       #       git add .
@@ -70,117 +113,41 @@ jobs:
       #       git pull --rebase origin ${{ github.head_ref }}
       #       git push --force-with-lease origin HEAD:${{ github.head_ref }}
       #     fi
-
-  lint_code:
-    name: Lint Code
-    runs-on: ubuntu-latest
-    outputs:
-      bash: ${{ steps.lint_code_cmd.outputs.bash }}
-    steps:
-      - uses: actions/checkout@v4
-      - uses: oven-sh/setup-bun@v2
-      - run: bun install
-      - id: lint_code_cmd
-        name: Lint Code
-        run: |
-          {
-            echo "bash<<EOF"
-            echo "$(bun run lint:code)"
-            echo "EOF"
-          } >> $GITHUB_OUTPUT
-
-  lint_knip:
-    name: Lint Knip
-    runs-on: ubuntu-latest
-    outputs:
-      bash: ${{ steps.lint_knip_cmd.outputs.bash }}
-    steps:
-      - uses: actions/checkout@v4
-      - uses: oven-sh/setup-bun@v2
-      - run: bun install
-      - id: lint_knip_cmd
-        name: Lint Knip
-        run: |
-          {
-            echo "bash<<EOF"
-            echo "$(bun run lint:knip --reporter markdown)"
-            echo "EOF"
-          } >> $GITHUB_OUTPUT
-
-  lint_markdown:
-    name: Lint Markdown
-    runs-on: ubuntu-latest
-    outputs:
-      bash: ${{ steps.lint_markdown_cmd.outputs.bash }}
-    steps:
-      - uses: actions/checkout@v4
-      - uses: oven-sh/setup-bun@v2
-      - run: bun install
-      - id: lint_markdown_cmd
-        name: Lint Markdown
-        run: |
-          {
-            echo "bash<<EOF"
-            echo "$(bun run lint:md)"
-            echo "EOF"
-          } >> $GITHUB_OUTPUT
-
-  lint_cspell:
-    name: Lint CSpell
-    runs-on: ubuntu-latest
-    outputs:
-      bash: ${{ steps.lint_cspell_cmd.outputs.bash }}
-    steps:
-      - uses: actions/checkout@v4
-      - uses: oven-sh/setup-bun@v2
-      - run: bun install
-      - id: lint_cspell_cmd
-        name: Lint CSpell
-        run: |
-          {
-            echo "bash<<EOF"
-            echo "$(bun run lint:cspell)"
-            echo "EOF"
-          } >> $GITHUB_OUTPUT
-
-  build:
-    name: Build
-    needs: [format_code, lint_code, lint_knip, lint_markdown, lint_cspell]
-    runs-on: ubuntu-latest
-    outputs:
-      packages_bash: ${{ steps.build_packages_cmd.outputs.bash }}
-      website_bash: ${{ steps.build_website_cmd.outputs.bash }}
-    steps:
-      - uses: actions/checkout@v4
-      - uses: oven-sh/setup-bun@v2
-      - run: bun install
       - name: Build Packages
-        id: build_packages_cmd
+        id: build_packages
+        continue-on-error: true
+        env:
+          CI: true
         run: |
+          set +e
           {
             echo "bash<<EOF"
-            echo "$(CI=true bun run build:packages)"
+            echo "$(bun run build:packages --output-style=stream)"
             echo "EOF"
           } >> $GITHUB_OUTPUT
-      - name: Build Website
-        id: build_website_cmd
-        run: |
-          {
-            echo "bash<<EOF"
-            echo "$(CI=true bun run build:www)"
-            echo "EOF"
-          } >> $GITHUB_OUTPUT
+          echo "exitcode=$?" >> $GITHUB_OUTPUT
 
-  tests:
+      # - name: Build Website
+      #   id: build_website
+      #   env:
+      #     CI: true
+      #   run: |
+      #     {
+      #       echo "bash<<EOF"
+      #       echo "$(bun run build:www)"
+      #       echo "EOF"
+      #     } >> $GITHUB_OUTPUT
+
+  code_tests:
     name: Tests
     runs-on: ubuntu-latest
     outputs:
-      bash: ${{ steps.tests_cmd.outputs.bash }}
+      bash: ${{ steps.tests.outputs.bash }}
     steps:
       - uses: actions/checkout@v4
       - uses: oven-sh/setup-bun@v2
       - run: bun install
-      - id: tests_cmd
+      - id: tests
         name: Tests
         run: |
           {
@@ -191,23 +158,29 @@ jobs:
 
   workflow_status:
     name: Workflow status
-    needs: [format_code, lint_code, lint_knip, lint_markdown, lint_cspell, build]
+    needs: [code_checks, code_tests]
     if: ${{ always() && !cancelled()  }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - run: |
-          echo "## ${{ needs.lint_code.result == 'success' && '✅' || '❌' }} Lint Code" >> $GITHUB_STEP_SUMMARY
-          echo "${{ needs.lint_code.outputs.bash }}" >> $GITHUB_STEP_SUMMARY
-          echo "## ${{ needs.lint_knip.result == 'success' && '✅' || '❌' }} Lint Knip" >> $GITHUB_STEP_SUMMARY
-          echo "${{ needs.lint_knip.outputs.bash }}" >> $GITHUB_STEP_SUMMARY
-          echo "## ${{ needs.lint_markdown.result == 'success' && '✅' || '❌' }} Lint Markdown" >> $GITHUB_STEP_SUMMARY
-          echo "${{ needs.lint_markdown.outputs.bash }}" >> $GITHUB_STEP_SUMMARY
-          echo "## ${{ needs.lint_cspell.result == 'success' && '✅' || '❌' }} Lint CSpell" >> $GITHUB_STEP_SUMMARY
-          echo "${{ needs.lint_cspell.outputs.bash }}" >> $GITHUB_STEP_SUMMARY
-          echo "## ${{ needs.build.result == 'success' && '✅' || '❌' }} Build" >> $GITHUB_STEP_SUMMARY
-          echo "${{ needs.build.outputs.website_bash }}" >> $GITHUB_STEP_SUMMARY
-          echo "${{ needs.build.outputs.packages_bash }}" >> $GITHUB_STEP_SUMMARY
+          echo "<details ${{ needs.code_checks.result == 'success' && 'open' || '' }}><summary><h2>" >> $GITHUB_STEP_SUMMARY
+          echo "${{ needs.code_checks.result == 'success' && '✅' || '❌' }} Lint Code" >> $GITHUB_STEP_SUMMARY
+          echo "</h2></summary> ${{ needs.code_checks.outputs.format_code }} </details>" >> $GITHUB_STEP_SUMMARY
+          echo "<details ${{ needs.code_checks.result == 'success' && 'open' || '' }}><summary>" >> $GITHUB_STEP_SUMMARY
+          echo "${{ needs.code_checks.result == 'success' && '✅' || '❌' }} Lint Knip" >> $GITHUB_STEP_SUMMARY
+          echo "</summary> ${{ needs.code_checks.outputs.lint_knip }} </details>" >> $GITHUB_STEP_SUMMARY
+          echo "<details ${{ needs.code_checks.result == 'success' && 'open' || '' }}><summary>" >> $GITHUB_STEP_SUMMARY
+          echo "${{ needs.code_checks.result == 'success' && '✅' || '❌' }} Lint Markdown" >> $GITHUB_STEP_SUMMARY
+          echo "</summary> ${{ needs.code_checks.outputs.lint_markdown }} </details>" >> $GITHUB_STEP_SUMMARY
+          echo "<details ${{ needs.code_checks.result == 'success' && 'open' || '' }}><summary>" >> $GITHUB_STEP_SUMMARY
+          echo "${{ needs.code_checks.result == 'success' && '✅' || '❌' }} Lint CSpell" >> $GITHUB_STEP_SUMMARY
+          echo "</summary> ${{ needs.code_checks.outputs.lint_cspell }} </details>" >> $GITHUB_STEP_SUMMARY
+          echo "<details ${{ needs.code_checks.result == 'success' && 'open' || '' }}><summary>" >> $GITHUB_STEP_SUMMARY
+          echo "${{ needs.code_checks.outputs.build_packages.exitcode == 0 && '✅' || '❌' }} Build" >> $GITHUB_STEP_SUMMARY
+          echo "</summary>" >> $GITHUB_STEP_SUMMARY
+          echo "${{ needs.code_checks.outputs.build_packages }} </details>" >> $GITHUB_STEP_SUMMARY
+        # echo "${{ needs.code_checks.outputs.build_website }}" >> $GITHUB_STEP_SUMMARY
       # - uses: marocchino/sticky-pull-request-comment@v2
       #   if: ${{ github.event_name == 'pull_request' }}
       #   with:
